"""initial tables

Revision ID: 000df49a0870
Revises: 
Create Date: 2026-04-08 20:19:23.251473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000df49a0870'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('safe_mode', sa.Boolean(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('hormonal_profile', sa.Enum('male', 'female', 'average', 'katch', 'hrt', name='hormonalprofile'), nullable=True),
    sa.Column('hrt_type', sa.Enum('estrogen', 'testosterone', name='hrttype'), nullable=True),
    sa.Column('hrt_months', sa.Integer(), nullable=True),
    sa.Column('navy_profile', sa.Enum('male', 'female', 'average', 'blend', name='navyprofile'), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('neck_cm', sa.Float(), nullable=True),
    sa.Column('hip_cm', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'very_active', 'extreme', name='activitylevel'), nullable=True),
    sa.Column('goal', sa.Enum('lose', 'maintain', 'gain', name='goal'), nullable=True),
    sa.Column('pace_kg_per_week', sa.Float(), nullable=True),
    sa.Column('metabolic_conditions', sa.Text(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('bmr', sa.Float(), nullable=True),
    sa.Column('tdee', sa.Float(), nullable=True),
    sa.Column('target_kcal', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('custom_kcal', sa.Float(), nullable=True),
    sa.Column('custom_protein', sa.Float(), nullable=True),
    sa.Column('custom_fat', sa.Float(), nullable=True),
    sa.Column('custom_carbs', sa.Float(), nullable=True),
    sa.Column('uses_custom_goals', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein_g', sa.Float(), nullable=True),
    sa.Column('total_fat_g', sa.Float(), nullable=True),
    sa.Column('total_carbs_g', sa.Float(), nullable=True),
    sa.Column('total_fiber_g', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.create_table('food_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('fdc_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('amount_g', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('meal', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_logs_log_date'), 'food_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_food_logs_user_id'), 'food_logs', ['user_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('fdc_id', sa.Integer(), nullable=True),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('amount_g', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_food_logs_user_id'), table_name='food_logs')
    op.drop_index(op.f('ix_food_logs_log_date'), table_name='food_logs')
    op.drop_table('food_logs')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
